### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by evando646** [Micke1101/OSTicket-plugin-TinyMCE#21]
Could you provide proper installation notes?

I could not get this working atm.

**Comment by mckaygerhard** [comment]
this are a crap development no documentation and only images.. the "osticket" directory refers to root of the installation, so you must paste a ln -s to the root diurectory of installation:
`ln -s osticket/js/tinymce ../../../js/tinymce` and then later got a php error

**Comment by MrAnonymouse** [comment]
The documentation is about as poor as I've ever seen.  Anything is better than this documentation, I actually took the time to register an account on GitHub for the first time in over 8 years of using GitHub just to say stay away from this product since the documentation is THIS BAD... it is HORRIBLE!

**Comment by stevland** [comment]
"I actually took the time to register an account on GitHub for the first time in over 8 years of using GitHub just to say stay away from this product"

@MrAnonymouse Good for you, bud! I noticed the documentation wasn't great, but I chose a different path. Whereas you chose to scold @Micke1101 for his free plugin, I used a similar amount of time to actually install the plugin and play around with it until I got it working. But different strokes I guess.

**Comment by MrAnonymouse** [comment]
I installed it, I then played around with it and even tried the cloud and clearing cache... I dropped the folders 3 parent folders back like he suggests with copy, I tried to also do the same thing 2 and 1 parent folder.  I also tried changing permissions and then deleted everything and tried all the steps I mentioned again because I thought I'd made too many changes... so this time I did a drag and drop from the original archive and replaced files that were duplicates with the ones from the archive... then when that didn't work I did the same thing in reverse (instead of bottom up I did it top down).  Finally, I decided the amount of work I put into this wasn't worth the time since the mod developer didn't take the time to write the one or two sentences required or put the files in the correct directories.  It's extremely easy to create, and publicize, files / archive these days.  What this person has done caused my ticket system to break without me noticing for about 15-20 minutes.  So, instead of someone else having their support ticket system go down I figured I'd warn them away.

Cheers!

**Comment by stevland** [comment]
Fair enough. I was being cheeky, obviously. I just felt defensive on behalf of @Micke1101 because I really appreciate this plugin.

If it helps, I believe I may have had more success when installing OSTicket-plugin-TinyMCE because I read [this thread](http://osticket.com/forum/discussion/91133/plugin-tinymce/p1).

**Comment by mckaygerhard** [comment]
documentation it's about the 40% of any development.. (except for stupid windosers users) so @MrAnonymouse have right in some degree, @stevland take in consideration how bad documented its this project..

i made a pull rq1uest to solve it:
https://github.com/Micke1101/OSTicket-plugin-TinyMCE/pull/23/files

fixed this and some other problems, of course for linux only.. "guin"dows users have their "click click click" copyright Mocosoft

**Comment by Micke1101** [comment]
@mckaygerhard and @MeAnonymouse
Sorry to hear that you feel this way, i really don’t use github that much, you’d either have to tag me here or talk in the thread on the forum.
As a note aswell if you read the post on the forum it states that this plugin is done as a experiment and not something i intended for production since it wasn’t completed due to time shortage.

**Comment by mckaygerhard** [comment]
hi @Micke1101 i can make some fixed by traking the forum threath and trying to backported to the repository.. if you can mantain in alert for my notifications.. 

lest take in consideration that ospos forum its a clear "propaganda" to paid services.. and help are only between users..

due github/gitlab mantai9n ordened and organized the task i must use it, i'll will notified in the forum only when i tested and solved complety an issue..

what do you thing about?

**Comment by Micke1101** [comment]
@mckaygerhard that sounds perfectly fine with me
